### PR TITLE
VBA-Fix. Better performance of VBA (2-3 times faster than Python) for multiplication of 1440 * 1440 matrices.

### PR DESCRIPTION
**Pull request by Excel-lent**
VBA-Fix. Better performance of VBA (2-3 times faster than Python) for multiplication of 1440 * 1440 matrices.

### CODE REVIEW

**Comment by Excel-lent** [comment]
1. Cell reading and writing is the slowest operation of VBA. Imagine multiplying matrices in C and reading values from file for each multiplication (of course with all kinds of checks and conversions from string to double) and writing intermediate results to another file.
2. In fact, well-prepared VBA is at least 2-3 times faster than the same Python code. On my not very fast Pentium 4417U, Python takes 651 seconds in a single thread and VBA only 210 seconds. The matrix size is the same in both cases: 1440 * 1440.
3. It's a good tradition in VBA repositories to extract the VBA code and place it near XLSM, since it's impossible to track XLSM changes in GitHub.

**Comment by Excel-lent** [comment]
@6DiegoDiego9, actually, it was really amazing to me that VBA is much faster than Python (even considering this discussion: https://stackoverflow.com/questions/30045508/python-loop-slower-than-excel-vba/67096174). I assumed pure Python could be 10% slower, but not more.

The other question is the using of external libraries. It's pretty easy to write a library that do some calculations in C#/C++ and use it in VBA. Then the performance of VBA would be comparable (at least I hope so) with NumPy, Numba, CuPy (only supported on systems with NVIDIA GPUs) and PyOpenCL (for all types of CPUs/GPUs). I wrote such a library (ClooWrapperVba) half a year ago to run OpenCL code from VBA, but I never compared the performance with PyOpenCL. Despite this, matrix multiplication was amazingly fast, even 2 times faster than native C# (OpenCL performance on my 4-threaded CPU was 8x faster than C# in a single thread).

**Comment by lkno0705** [comment]
Crazy.. Didn't know all this is possible! The initial VBA Application really only resulted from some basic VBA knowledge, gathered in the wild with access and a little bit of excel. It is quite astonishing that it is that much faster!

The old implementation was funny though.

Changes look fine to me.. Didn't check the xslm, because I don't have access to Excel anymore. So I can't benchmark it on the original System. However, if you want, feel free to add a comparison with your own system in the Readme, maybe in a new subsection with the specs of the benchmarked system!

I'll merge the request after I've got your reply whether you'll add it or not. Also crazy that this repo has some traffic.

Thanks for the contribution!

**Comment by Excel-lent** [comment]
@lkno0705, and I don't have access to Ryzen 9 3900X 😁
I propose a kind of compromise: on my Pentium 4417U Python takes 651 seconds, VBA - 210 s, so in the readme it should be 210 (VBA on 4417U) * (230 (Python on Ryzen) / 651 (Python on 4417U). ) = 74s.
I think for clarification in Radme.md you have to write something like this:
"Results were obtained on a different CPU and scaled to Python performance". If someone will run VBA on Ryzen, they can replace it with new results, but I don't think the difference will be higher than 10%.

By the way, do you need matrix multiplication in PowerShell?

**Comment by marcauberer** [comment]
@Excel-lent every contribution is much appreciated. PowerShell is missing, so I'd say: go for it!

**Comment by 6DiegoDiego9** [comment]
@Excel-lent, I didn't understand your last sentence: do you mean that VBA+[ClooWrapperVba](https://github.com/Excel-lent/ClooWrapperVBA) was faster than C# alone or even than C#+OpenCL?

During the past few years, I always searching for a way to use GPU from VBA, so when I saw your library [ClooWrapperVba](https://github.com/Excel-lent/ClooWrapperVBA)) yesterday, I was amazed and tried it immediately.
However, matrix calculations and AI are out of my scope, my interest in performance is mainly focused on comparing numbers rather than multiplying them, using large amounts of binary numeric data.
At first glance ClooWrapperVba seems like a complex library to me, so I try to ask to you an opinion before investing time to understand it: what kind of operations can it accelerate?

By the way you might also be interested in the crazy [TwinBASIC ](https://twinbasic.com/)project, which can make VBA code faster:
"Compiled code emitted by twinBASIC Preview 1 is unoptimized native code. Even though the output code is unoptimized, it is typically much faster than VBA (or VB6’s p-code compilation), simply due to it being native machine code.
Work is already underway (planned 2023-Q1) to integrate LLVM into twinBASIC so that we can grab some of the amazing benefits it offers for code generation."
It also adds native multithreading to VBA!

**Comment by Excel-lent** [comment]
@lkno0705, I would appreciate if you would merge my pull request as is.

I don't think adding a new subsection with my benchmarks makes sense. I think that was a pretty questionable decision to use any CPU/GPU as a reference. For me, a better decision would be to use one language as a reference and measure the performance of other languages relative to it. A good example of a reference language is Python (cross-platform, widely used). What will we do in 20 years when your Ryzen is gone? Also, you can add some platform independent relative performance statistics (average performance and standard deviation among several other platforms). But those are just my thoughts...

Frohe Weihnachten und herzliche Grüße aus Dresden!

**Comment by Excel-lent** [comment]
@6DiegoDiego9, I've started a [new discussion](https://github.com/Excel-lent/ClooWrapperVBA/discussions/3) at ClooWrapperVBA page as it is outside the scope of this pull request.

**Comment by lkno0705** [comment]
> @lkno0705, I would appreciate if you would merge my pull request as is.
> 
> 
> 
> I don't think adding a new subsection with my benchmarks makes sense. I think that was a pretty questionable decision to use any CPU/GPU as a reference. For me, a better decision would be to use one language as a reference and measure the performance of other languages relative to it. A good example of a reference language is Python (cross-platform, widely used). What will we do in 20 years when your Ryzen is gone? Also, you can add some platform independent relative performance statistics (average performance and standard deviation among several other platforms). But those are just my thoughts...
> 
> 
> 
> Frohe Weihnachten und herzliche Grüße aus Dresden!

I totally agree! At the time this repo was created, this was the fastest cpu we could get our hands on and we wanted to see what it can do out of curiosity and then somehow we started benchmarking languages during our lectures 😅. I'll merge it!

Frohe Weihanchten!

**Comment by Excel-lent** [comment]
Thanks a lot! 😊👍

**Comment by sancarn** [comment]
Merging of this PR should have been combined with updating the readme? But it seems the readme remains the same?

I was discussing this with @KallunWillock and we believe there is actually a multithreaded variant use pure excel vba:

```vb
Dim MatrixA As Variant, MatrixB As Variant, MatrixC As Variant
MatrixA = Application.RandArray(1440, 1440, 1, 11, False)
MatrixB = Application.RandArray(1440, 1440, 1, 11, False)

Dim Start As Single: Start = Timer
MatrixC = Application.MMult(MatrixA, MatrixB)
Debug.Print "Threaded Excel VBA: " & Timer - Start
```

Compared to the single threaded vba sample, this performs the operations in a quarter of the time.

> Single Excel VBA: 105.6172
> Threaded Excel VBA: 27.83203

In a sense, though, this could be relative to using a library. We believe the calculation is threaded but have no real way of proving that fact.

**Comment by Excel-lent** [comment]
Hello Sancarn, nice to see you again!

Leon ([@lkno0705](https://github.com/lkno0705)) already explained the problem of updating the readme file: 

> I can't compare it with the original system.

There is simply no reference to compare the benchmarks. Even my statement that VBA is 2-3 times faster than Python will be wrong with a new version of Python or Excel.

Still, your and @KallunWillock’s suggestion is really good. I forgot that Excel has built-in functions (mainly because I rarely use them). When making a pull request, you should probably write which versions of Excel it is compatible with. The reason is that the "RandArray" function works in Excel 2021. Secondly, I think that in the old versions of Excel (mine is Excel 2007) you should use "WorksheetFunction" except "Application". Third, I don't think it's an effect of multithreading. The function was simply written in C++ or another language to be faster than pure VBA.

Still, why not? This is a good reason to say that Excel is 12 times faster than Python. 😁

**Comment by sancarn** [comment]
> Still, why not? This is a good reason to say that Excel is 12 times faster than Python. 😁

Our thoughts align 🤣

**Pull request merged**
